In [7]:
# series
import pandas
from pandas import Series

fandango = pandas.read_csv(
    "E:\Workspace\jupyter_notebook\\notebook_idata_lesson01\pandas\\fandango_score_comparison.csv")
series_film = fandango["FILM"]
print(series_film.head(3))
print(series_film.shape)
series_rt = fandango["RottenTomatoes"]
print(series_rt[:3])

0    Avengers: Age of Ultron (2015)
1                 Cinderella (2015)
2                    Ant-Man (2015)
Name: FILM, dtype: object
(146,)
0    74
1    85
2    80
Name: RottenTomatoes, dtype: int64

In [18]:
film_names = series_film.values
# film_names的格式是ndarray
print(type(film_names))
print(film_names[:3])
rt_scores = series_rt.values
# 创建一个Series，value是rt_scores,index是film_names，两个都是ndarray
# 也就是index是object(string)了
series_custom = Series(rt_scores, index=film_names)
print(series_custom[:3])
# 用string作为index来选择列
series_custom[["Avengers: Age of Ultron (2015)", "Cinderella (2015)"]]

<class 'numpy.ndarray'>
['Avengers: Age of Ultron (2015)' 'Cinderella (2015)' 'Ant-Man (2015)']
Avengers: Age of Ultron (2015)    74
Cinderella (2015)                 85
Ant-Man (2015)                    80
dtype: int64

Avengers: Age of Ultron (2015)    74
Cinderella (2015)                 85
dtype: int64

In [20]:
# series_custom也可以使用数字下标来访问
series_custom[3:6]

Do You Believe? (2015)           18
Hot Tub Time Machine 2 (2015)    14
The Water Diviner (2015)         63
dtype: int64

In [21]:
# 对Series进行计算
series_custom *= 10
print(series_custom[:3])

Avengers: Age of Ultron (2015)    740
Cinderella (2015)                 850
Ant-Man (2015)                    800
dtype: int64

In [34]:
fandango = pandas.read_csv(
    "E:\Workspace\jupyter_notebook\\notebook_idata_lesson01\pandas\\fandango_score_comparison.csv")
# 重新指定dataFrame的index
fandango_films = fandango.set_index("FILM", drop=False)
print(fandango_films.index)

Index(['Avengers: Age of Ultron (2015)', 'Cinderella (2015)', 'Ant-Man (2015)',
       'Do You Believe? (2015)', 'Hot Tub Time Machine 2 (2015)',
       'The Water Diviner (2015)', 'Irrational Man (2015)', 'Top Five (2014)',
       'Shaun the Sheep Movie (2015)', 'Love & Mercy (2015)',
       ...
       'The Woman In Black 2 Angel of Death (2015)', 'Danny Collins (2015)',
       'Spare Parts (2015)', 'Serena (2015)', 'Inside Out (2015)',
       'Mr. Holmes (2015)', ''71 (2015)', 'Two Days, One Night (2014)',
       'Gett: The Trial of Viviane Amsalem (2015)',
       'Kumiko, The Treasure Hunter (2015)'],
      dtype='object', name='FILM', length=146)

In [37]:
# 使用string作为index来访问数据，按照字典序的顺序排序
# print(fandango_films["Avengers: Age of Ultron (2015)":"Hot Tub Time Machine 2 (2015)"])

# loc访问数据
print(fandango_films.loc['Kumiko, The Treasure Hunter (2015)'])

FILM                          Kumiko, The Treasure Hunter (2015)
RottenTomatoes                                                87
RottenTomatoes_User                                           63
Metacritic                                                    68
Metacritic_User                                              6.4
IMDB                                                         6.7
Fandango_Stars                                               3.5
Fandango_Ratingvalue                                         3.5
RT_norm                                                     4.35
RT_user_norm                                                3.15
Metacritic_norm                                              3.4
Metacritic_user_nom                                          3.2
IMDB_norm                                                   3.35
RT_norm_round                                                4.5
RT_user_norm_round                                             3
Metacritic_norm_round                                        3.5
Metacritic_user_norm_round                                     3
IMDB_norm_round                                              3.5
Metacritic_user_vote_count                                    19
IMDB_user_vote_count                                        5289
Fandango_votes                                                41
Fandango_Difference                                            0
Name: Kumiko, The Treasure Hunter (2015), dtype: object

In [38]:
# lambda
fandango.head()

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>FILM</th>
      <th>RottenTomatoes</th>
      <th>RottenTomatoes_User</th>
      <th>Metacritic</th>
      <th>Metacritic_User</th>
      <th>IMDB</th>
      <th>Fandango_Stars</th>
      <th>Fandango_Ratingvalue</th>
      <th>RT_norm</th>
      <th>RT_user_norm</th>
      <th>...</th>
      <th>IMDB_norm</th>
      <th>RT_norm_round</th>
      <th>RT_user_norm_round</th>
      <th>Metacritic_norm_round</th>
      <th>Metacritic_user_norm_round</th>
      <th>IMDB_norm_round</th>
      <th>Metacritic_user_vote_count</th>
      <th>IMDB_user_vote_count</th>
      <th>Fandango_votes</th>
      <th>Fandango_Difference</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Avengers: Age of Ultron (2015)</td>
      <td>74</td>
      <td>86</td>
      <td>66</td>
      <td>7.1</td>
      <td>7.8</td>
      <td>5.0</td>
      <td>4.5</td>
      <td>3.70</td>
      <td>4.3</td>
      <td>...</td>
      <td>3.90</td>
      <td>3.5</td>
      <td>4.5</td>
      <td>3.5</td>
      <td>3.5</td>
      <td>4.0</td>
      <td>1330</td>
      <td>271107</td>
      <td>14846</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Cinderella (2015)</td>
      <td>85</td>
      <td>80</td>
      <td>67</td>
      <td>7.5</td>
      <td>7.1</td>
      <td>5.0</td>
      <td>4.5</td>
      <td>4.25</td>
      <td>4.0</td>
      <td>...</td>
      <td>3.55</td>
      <td>4.5</td>
      <td>4.0</td>
      <td>3.5</td>
      <td>4.0</td>
      <td>3.5</td>
      <td>249</td>
      <td>65709</td>
      <td>12640</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Ant-Man (2015)</td>
      <td>80</td>
      <td>90</td>
      <td>64</td>
      <td>8.1</td>
      <td>7.8</td>
      <td>5.0</td>
      <td>4.5</td>
      <td>4.00</td>
      <td>4.5</td>
      <td>...</td>
      <td>3.90</td>
      <td>4.0</td>
      <td>4.5</td>
      <td>3.0</td>
      <td>4.0</td>
      <td>4.0</td>
      <td>627</td>
      <td>103660</td>
      <td>12055</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Do You Believe? (2015)</td>
      <td>18</td>
      <td>84</td>
      <td>22</td>
      <td>4.7</td>
      <td>5.4</td>
      <td>5.0</td>
      <td>4.5</td>
      <td>0.90</td>
      <td>4.2</td>
      <td>...</td>
      <td>2.70</td>
      <td>1.0</td>
      <td>4.0</td>
      <td>1.0</td>
      <td>2.5</td>
      <td>2.5</td>
      <td>31</td>
      <td>3136</td>
      <td>1793</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Hot Tub Time Machine 2 (2015)</td>
      <td>14</td>
      <td>28</td>
      <td>29</td>
      <td>3.4</td>
      <td>5.1</td>
      <td>3.5</td>
      <td>3.0</td>
      <td>0.70</td>
      <td>1.4</td>
      <td>...</td>
      <td>2.55</td>
      <td>0.5</td>
      <td>1.5</td>
      <td>1.5</td>
      <td>1.5</td>
      <td>2.5</td>
      <td>88</td>
      <td>19560</td>
      <td>1021</td>
      <td>0.5</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 22 columns</p>
</div>